Revert "Use 3.11-slim as base image (#259)" (#304)
This reverts commit 93ab8e878b6ea5a4d5e27ef09d2a510cd2fce80b.

The OpenStack SDK is not yet happy with Python 3.11:

AttributeError: module 'inspect' has no attribute 'getargspec'.
Did you mean: 'getargs'?

More details: https://github.com/pyinvoke/invoke/issues/833

Closes osism/issues#392

Signed-off-by: Christian Berendt <berendt@osism.tech>